# Uncomment the next line to define a global platform for your project
 platform :ios, '16.2'

target 'weatherApp' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for weatherApp

  target 'weatherAppTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'weatherAppUITests' do
    # Pods for testing
  end

  pod 'RealmSwift', '~>10'
  pod 'ProgressHUD'

end
